#!/bin/bash

# install Fabric
pip3 install -y Fabric

# Install dependencies
sudo apt-get update
sudo apt-get install -y libffi-dev libssl-dev build-essential python3.4-dev libpython3-dev

# Install Python packages to their latest version
pip3 install --upgrade pyparsing appdirs setuptools cryptography bcrypt PyNaCl Fabric3

# Specific versions for certain packages
pip3 install setuptools==40.1.0
pip3 install cryptography==2.8
pip3 install bcrypt==3.1.7
pip3 install PyNaCl==1.3.0
pip3 install Fabric3==1.14.post1

echo "Installation completed."

